/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package womens_safety_app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import womens_safety_app.Login_Page;

/**
 *
 * @author Admin
 */
public class Register_Page extends javax.swing.JFrame {

    /**
     * Creates new form Register_Page
     */
    public Register_Page() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        l_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        re_pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        u_name = new javax.swing.JTextField();
        f_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        age = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        phone_no = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registeration Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(179, 104, 136, 35);

        l_name.setBackground(new java.awt.Color(102, 102, 102));
        l_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        l_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(l_name);
        l_name.setBounds(342, 104, 378, 35);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Retype Password:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 263, 215, 35);

        re_pass.setBackground(new java.awt.Color(102, 102, 102));
        re_pass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        re_pass.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(re_pass);
        re_pass.setBounds(342, 263, 378, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(186, 157, 129, 35);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(176, 51, 139, 35);

        u_name.setBackground(new java.awt.Color(102, 102, 102));
        u_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        u_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(u_name);
        u_name.setBounds(342, 157, 378, 35);

        f_name.setBackground(new java.awt.Color(102, 102, 102));
        f_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        f_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(f_name);
        f_name.setBounds(342, 51, 378, 35);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(191, 210, 124, 35);

        pass.setBackground(new java.awt.Color(102, 102, 102));
        pass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(pass);
        pass.setBounds(342, 210, 378, 35);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Age:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(261, 316, 54, 35);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(212, 431, 103, 43);

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("click here to login");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);
        jLabel9.setBounds(279, 692, 139, 24);

        jButtonRegister.setBackground(new java.awt.Color(51, 255, 0));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegister);
        jButtonRegister.setBounds(382, 619, 134, 47);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(200, 619, 127, 47);

        add.setBackground(new java.awt.Color(102, 102, 102));
        add.setColumns(20);
        add.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setRows(5);
        jScrollPane1.setViewportView(add);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(342, 431, 378, 163);

        age.setBackground(new java.awt.Color(102, 102, 102));
        age.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel2.add(age);
        age.setBounds(342, 316, 378, 35);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone no.:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(186, 369, 129, 44);

        phone_no.setBackground(new java.awt.Color(102, 102, 102));
        phone_no.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phone_no.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(phone_no);
        phone_no.setBounds(342, 369, 378, 36);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\faust\\Documents\\NetBeansProjects\\Womens_Safety_App\\src\\womens_safety_app\\women-health-symbol.png")); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(210, 60, 510, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Login_Page lg=new Login_Page();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String first_name=f_name.getText();
        String last_name=l_name.getText();
        String user_name=u_name.getText();
        String password=String.valueOf(pass.getPassword());
        String retype_password=String.valueOf(re_pass.getPassword());
        String Age= age.getText();
        String phone= phone_no.getText();
        String address=add.getText();
        
        
        if(first_name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter first name !!","Missing",3);
        }
        else if(user_name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter a username !!","Missing",3);
        }
        else if(checkUser(user_name))
        {
            JOptionPane.showMessageDialog(null, "This Username exists. Please fill again!!","Incorrect",2);
            u_name.setText("");
        }
        else if(password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter a password !!","Missing",3);
        }
        else if(!password.equals(retype_password))
        {
            JOptionPane.showMessageDialog(null, "Retype the password !!","Incorrect",2);
            re_pass.setText("");
        }
        else if(Age.equals(""))
        {
                JOptionPane.showMessageDialog(null, "Enter your age !!","Missing",3);
        }
        else if(Age.length()>2)
        {
                JOptionPane.showMessageDialog(null, "Enter valid age !!","Missing",3);
                age.setText("");
        }
        else if(phone.equals(""))
        {
                JOptionPane.showMessageDialog(null, "Enter phone number !!","Missing",3);
        }
        else if(phone.length() > 10)
        {
                JOptionPane.showMessageDialog(null, "Enter a valid phone number !!","Missing",3);
                phone_no.setText("");
        }
        else if(address.equals(""))
        {
                JOptionPane.showMessageDialog(null, "Enter an address !!","Missing",3);
        }
        else
        {
        try
        {
           // Class.forName("com.mysql.jdbc.Driver");com.mysql.cj.jdbc.Driver 
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/womens_safety_app", "root", "joel@2002");
        
            PreparedStatement ps;
            String Query="INSERT INTO `womens_safety_app`.`registered_users` (`First Name`, `Last Name`, `Username`, `Password`, `Retype Password`, `AGE`, `Phone Number`, `Address`) VALUES (?, ?, ?, ?, ?, ?, ? ,?)";
            ps=con.prepareStatement(Query);
            ps.setString(1, first_name);
            ps.setString(2, last_name);
            ps.setString(3, user_name);
            ps.setString(4, password);
            ps.setString(5, retype_password);
            ps.setString(6, Age);
            ps.setString(7, phone);
            ps.setString(8, address);
            
            
            if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null, "User Registered Successfully","Success",1);
                Login_Page lp=new Login_Page();
                lp.setVisible(true);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        }
        
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed
    public boolean checkUser(String user)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean check_user=false;
        String query="SELECT * FROM womens_safety_app.registered_users where Username=?";
        try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/womens_safety_app", "root", "joel@2002");
            ps=con.prepareStatement(query);
            ps.setString(1, user);
            rs=ps.executeQuery();
            if(rs.next())
            {
                check_user=true;
            }
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
        
        return check_user;
    }
    
    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private javax.swing.JTextField age;
    private javax.swing.JTextField f_name;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField l_name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField phone_no;
    private javax.swing.JPasswordField re_pass;
    private javax.swing.JTextField u_name;
    // End of variables declaration//GEN-END:variables
}
